### ISSUE TITLE
Magnet links not working

### ISSUE THREAD

**Issue by remissao** [Thomaslegravier/DSDownload#2]
I tried using several Magnet links but I always get the same error:

![image](https://user-images.githubusercontent.com/4529190/79904877-abd0f800-8415-11ea-8197-d2d3145cf495.png)

Here's one fo the links I tried:
[magnet:?xt=urn:btih:dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c&dn=Big+Buck+Bunny&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fbig-buck-bunny.torrent](url)

**Comment by Thomaslegravier** [comment]
Holà @remissao ,
A new version is available and your problem is now fixed.
You will be able to start a download directly after a click on a magnet link un safari too ;)

**Comment by remissao** [comment]
@Thomaslegravier 
Thanks!
Where can I find the compiled Mac app? I actually tried downloading the source but I get an error when I try to build it in Xcode.

**Comment by Thomaslegravier** [comment]
@remissao yes you need sign the application with a developper certificate.
I will prepare a next release (dmg) in few days. I'll keep you in touch.

**Comment by Thomaslegravier** [comment]
Hello @remissao !
New release of DSDownload is now available with a dmg file >>> https://github.com/Thomaslegravier/DSDownload/releases
